{"uid":"db134c8df2f584b7","name":"test_chainId[Test for Amplitude]","fullName":"tests.test_network_parameters.TestChainId#test_chainId","historyId":"b6fb68db7ac371084e54542bba6989bd","time":{"start":1670170960090,"stop":1670170960309,"duration":219},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fc240260280>\nchain = <tests.utils.chain_model.Chain object at 0x7fc24030a880>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fc24030a880>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Amplitude\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fc240260280>\nchain = <tests.utils.chain_model.Chain object at 0x7fc24030a880>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fc24030a880>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Amplitude\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"dd461ee5e8e1eaa","name":"stdout","source":"dd461ee5e8e1eaa.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestChainId"},{"name":"host","value":"fv-az343-503"},{"name":"thread","value":"1727-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fc24030a880>"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"222cc89b3e49a6f7","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670170949868,"stop":1670170950083,"duration":215}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":60,"skipped":0,"passed":237,"unknown":0,"total":297},"items":[{"uid":"60a4c10dcac141b0","reportUrl":"https://nova-wallet.github.io/test-runner/2021//#testresult/60a4c10dcac141b0","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670157817121,"stop":1670157817149,"duration":28}},{"uid":"3ede4b2845bf22de","reportUrl":"https://nova-wallet.github.io/test-runner/2020//#testresult/3ede4b2845bf22de","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670142924670,"stop":1670142924729,"duration":59}},{"uid":"7ee5fa474d344d1b","reportUrl":"https://nova-wallet.github.io/test-runner/2019//#testresult/7ee5fa474d344d1b","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670128511733,"stop":1670128511788,"duration":55}},{"uid":"83dd08a36cbf8d3f","reportUrl":"https://nova-wallet.github.io/test-runner/2018//#testresult/83dd08a36cbf8d3f","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670117246000,"stop":1670117246020,"duration":20}},{"uid":"9485cc2815e43e38","reportUrl":"https://nova-wallet.github.io/test-runner/2017//#testresult/9485cc2815e43e38","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670099521935,"stop":1670099521965,"duration":30}},{"uid":"ba9e64c392fa357f","reportUrl":"https://nova-wallet.github.io/test-runner/2016//#testresult/ba9e64c392fa357f","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670085409149,"stop":1670085409488,"duration":339}},{"uid":"a5eb09770f21d0e3","reportUrl":"https://nova-wallet.github.io/test-runner/2015//#testresult/a5eb09770f21d0e3","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670071336861,"stop":1670071336899,"duration":38}},{"uid":"4a524793a9ea62a2","reportUrl":"https://nova-wallet.github.io/test-runner/2014//#testresult/4a524793a9ea62a2","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670056563846,"stop":1670056564033,"duration":187}},{"uid":"a1a071b2464d2a19","reportUrl":"https://nova-wallet.github.io/test-runner/2013//#testresult/a1a071b2464d2a19","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670042081276,"stop":1670042081307,"duration":31}},{"uid":"93f753b04f2e1884","reportUrl":"https://nova-wallet.github.io/test-runner/2012//#testresult/93f753b04f2e1884","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670030588437,"stop":1670030588731,"duration":294}},{"uid":"859cc33134cc40c4","reportUrl":"https://nova-wallet.github.io/test-runner/2011//#testresult/859cc33134cc40c4","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1670013185944,"stop":1670013186449,"duration":505}},{"uid":"8bcf9f897ac979eb","reportUrl":"https://nova-wallet.github.io/test-runner/2010//#testresult/8bcf9f897ac979eb","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669999075009,"stop":1669999075371,"duration":362}},{"uid":"7f8e053f46f8b5b7","reportUrl":"https://nova-wallet.github.io/test-runner/2009//#testresult/7f8e053f46f8b5b7","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669987161746,"stop":1669987162095,"duration":349}},{"uid":"ee0a12ee61f60f56","reportUrl":"https://nova-wallet.github.io/test-runner/2000//#testresult/ee0a12ee61f60f56","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669883926062,"stop":1669883926358,"duration":296}},{"uid":"74c493f40dee2153","reportUrl":"https://nova-wallet.github.io/test-runner/1999//#testresult/74c493f40dee2153","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669869407819,"stop":1669869407857,"duration":38}},{"uid":"214569239edd2b6b","reportUrl":"https://nova-wallet.github.io/test-runner/1998//#testresult/214569239edd2b6b","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669859096522,"stop":1669859096566,"duration":44}},{"uid":"e2bf98e304e5924d","reportUrl":"https://nova-wallet.github.io/test-runner/1997//#testresult/e2bf98e304e5924d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669840442328,"stop":1669840442363,"duration":35}},{"uid":"8d8d8b2dc6c4cc0a","reportUrl":"https://nova-wallet.github.io/test-runner/1996//#testresult/8d8d8b2dc6c4cc0a","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669826351870,"stop":1669826352042,"duration":172}},{"uid":"a2d32f7786a9a894","reportUrl":"https://nova-wallet.github.io/test-runner/1995//#testresult/a2d32f7786a9a894","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669812502943,"stop":1669812503272,"duration":329}},{"uid":"69a1d77df6903c81","reportUrl":"https://nova-wallet.github.io/test-runner/1994//#testresult/69a1d77df6903c81","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Amplitude","time":{"start":1669797483160,"stop":1669797483538,"duration":378}}]},"tags":[]},"source":"db134c8df2f584b7.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fc24030a880>"]}