{"uid":"91e2897728224363","name":"test_precision[Test for Parallel]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"e987411f220942949f89dbd7c1988344","time":{"start":1706054556698,"stop":1706054556698,"duration":0},"status":"failed","statusMessage":"Failed: Timeout 10 when creating connection: Parallel","statusTrace":"timeout = 10\nfunction = <bound method Chain.create_connection of <scripts.utils.chain_model.Chain object at 0x7f80502a2650>>\nargs = (), error_message = 'Timeout 10 when creating connection: Parallel'\n\n    def execute_with_timeout(timeout: int, function, args: tuple, error_message: str):\n        try:\n>           return func_timeout(timeout=timeout, func=function, args=args)\n\ntests/conftest.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ntimeout = 10\nfunc = <bound method Chain.create_connection of <scripts.utils.chain_model.Chain object at 0x7f80502a2650>>\nargs = (), kwargs = {}\n\n    def func_timeout(timeout, func, args=(), kwargs=None):\n        '''\n            func_timeout - Runs the given function for up to #timeout# seconds.\n    \n            Raises any exceptions #func# would raise, returns what #func# would return (unless timeout is exceeded), in which case it raises FunctionTimedOut\n    \n            @param timeout <float> - Maximum number of seconds to run #func# before terminating\n    \n            @param func <function> - The function to call\n    \n            @param args    <tuple> - Any ordered arguments to pass to the function\n    \n            @param kwargs  <dict/None> - Keyword arguments to pass to the function.\n    \n    \n            @raises - FunctionTimedOut if #timeout# is exceeded, otherwise anything #func# could raise will be raised\n    \n            If the timeout is exceeded, FunctionTimedOut will be raised within the context of the called function every two seconds until it terminates,\n            but will not block the calling thread (a new thread will be created to perform the join). If possible, you should try/except FunctionTimedOut\n            to return cleanly, but in most cases it will 'just work'.\n    \n            @return - The return value that #func# gives\n        '''\n    \n        if not kwargs:\n            kwargs = {}\n        if not args:\n            args = ()\n    \n        ret = []\n        exception = []\n        isStopped = False\n    \n        def funcwrap(args2, kwargs2):\n            try:\n                ret.append( func(*args2, **kwargs2) )\n            except FunctionTimedOut:\n                # Don't print traceback to stderr if we time out\n                pass\n            except Exception as e:\n                exc_info = sys.exc_info()\n                if isStopped is False:\n                    # Assemble the alternate traceback, excluding this function\n                    #  from the trace (by going to next frame)\n                    # Pytohn3 reads native from __traceback__,\n                    # python2 has a different form for \"raise\"\n                    e.__traceback__ = exc_info[2].tb_next\n                    exception.append( e )\n    \n        thread = StoppableThread(target=funcwrap, args=(args, kwargs))\n        thread.daemon = True\n    \n        thread.start()\n        thread.join(timeout)\n    \n        stopException = None\n        if thread.is_alive():\n            isStopped = True\n    \n            class FunctionTimedOutTempType(FunctionTimedOut):\n                def __init__(self):\n                    return FunctionTimedOut.__init__(self, '', timeout, func, args, kwargs)\n    \n            FunctionTimedOutTemp = type('FunctionTimedOut' + str( hash( \"%d_%d_%d_%d\" %(id(timeout), id(func), id(args), id(kwargs))) ), FunctionTimedOutTempType.__bases__, dict(FunctionTimedOutTempType.__dict__))\n    \n            stopException = FunctionTimedOutTemp\n            thread._stopThread(stopException)\n            thread.join(min(.1, timeout / 50.0))\n>           raise FunctionTimedOut('', timeout, func, args, kwargs)\nE           func_timeout.exceptions.FunctionTimedOut: Function create_connection (args=()) (kwargs={}) timed out after 10.000000 seconds.\n\n.venv/lib/python3.10/site-packages/func_timeout/dafunc.py:101: FunctionTimedOut\n\nDuring handling of the above exception, another exception occurred:\n\nrequest = <SubRequest 'chain_model' for <Function test_precision[Test for Parallel]>>\n\n    @pytest.fixture(scope=\"module\", params=get_substrate_chains(), ids=chain_names)\n    def chain_model(request) -> Chain:\n        chain = request.param\n>       execute_with_timeout(\n            timeout=FIXTURE_TIMEOUT,\n            function=chain.create_connection,\n            args=(),\n            error_message=f'Timeout {FIXTURE_TIMEOUT} when creating connection: {chain.name}'\n        )\n\ntests/conftest.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ntimeout = 10\nfunction = <bound method Chain.create_connection of <scripts.utils.chain_model.Chain object at 0x7f80502a2650>>\nargs = (), error_message = 'Timeout 10 when creating connection: Parallel'\n\n    def execute_with_timeout(timeout: int, function, args: tuple, error_message: str):\n        try:\n            return func_timeout(timeout=timeout, func=function, args=args)\n        except FunctionTimedOut:\n>           pytest.fail(msg=error_message)\nE           Failed: Timeout 10 when creating connection: Parallel\n\ntests/conftest.py:24: Failed","flaky":true,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":2,"retriesStatusChange":false,"beforeStages":[{"name":"chain_model","time":{"start":1706054526392,"stop":1706054536501,"duration":10109},"status":"failed","statusMessage":"Failed: Timeout 10 when creating connection: Parallel\n","statusTrace":"  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 46, in chain_model\n    execute_with_timeout(\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 24, in execute_with_timeout\n    pytest.fail(msg=error_message)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/outcomes.py\", line 194, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"chain_model","time":{"start":1706054541574,"stop":1706054551682,"duration":10108},"status":"failed","statusMessage":"Failed: Timeout 10 when creating connection: Parallel\n","statusTrace":"  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 46, in chain_model\n    execute_with_timeout(\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 24, in execute_with_timeout\n    pytest.fail(msg=error_message)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/outcomes.py\", line 194, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"chain_model","time":{"start":1706054556699,"stop":1706054566805,"duration":10106},"status":"failed","statusMessage":"Failed: Timeout 10 when creating connection: Parallel\n","statusTrace":"  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 907, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 46, in chain_model\n    execute_with_timeout(\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/tests/conftest.py\", line 24, in execute_with_timeout\n    pytest.fail(msg=error_message)\n  File \"/home/runner/work/test-runner/test-runner/nova-utils/.venv/lib/python3.10/site-packages/_pytest/outcomes.py\", line 194, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az915-576"},{"name":"thread","value":"2229-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain_model","value":"<scripts.utils.chain_model.Chain object at 0x7f80502a2650>"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"cbf17a47e23b1f66","status":"failed","statusDetails":"Failed: Timeout 10 when creating connection: Parallel","time":{"start":1706054541573,"stop":1706054541573,"duration":0}},{"uid":"e1806c90f4ebec30","status":"failed","statusDetails":"Failed: Timeout 10 when creating connection: Parallel","time":{"start":1706054526391,"stop":1706054526391,"duration":0}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":6,"broken":8,"skipped":0,"passed":768,"unknown":0,"total":782},"items":[{"uid":"d668bd216bae73c6","reportUrl":"https://novasamatech.github.io/test-runner/4568//#testresult/d668bd216bae73c6","status":"failed","statusDetails":"Failed: Timeout 10 when creating connection: Parallel","time":{"start":1706040119458,"stop":1706040119458,"duration":0}},{"uid":"510731527a7ddf0e","reportUrl":"https://novasamatech.github.io/test-runner/4567//#testresult/510731527a7ddf0e","status":"passed","time":{"start":1706025693836,"stop":1706025693836,"duration":0}},{"uid":"27422f3a75cfa034","reportUrl":"https://novasamatech.github.io/test-runner/4566//#testresult/27422f3a75cfa034","status":"passed","time":{"start":1706011290243,"stop":1706011290243,"duration":0}},{"uid":"52c15768c395d50c","reportUrl":"https://novasamatech.github.io/test-runner/4565//#testresult/52c15768c395d50c","status":"passed","time":{"start":1705996891622,"stop":1705996891622,"duration":0}},{"uid":"ec04f984096a6e60","reportUrl":"https://novasamatech.github.io/test-runner/4564//#testresult/ec04f984096a6e60","status":"failed","statusDetails":"Failed: Timeout 10 when creating connection: Parallel","time":{"start":1705982514452,"stop":1705982514452,"duration":0}},{"uid":"5d3da50b8ad637a2","reportUrl":"https://novasamatech.github.io/test-runner/4563//#testresult/5d3da50b8ad637a2","status":"passed","time":{"start":1705968140437,"stop":1705968140437,"duration":0}},{"uid":"99be8bc1f2689b5e","reportUrl":"https://novasamatech.github.io/test-runner/4562//#testresult/99be8bc1f2689b5e","status":"passed","time":{"start":1705953681079,"stop":1705953681079,"duration":0}},{"uid":"2d211eee335a0823","reportUrl":"https://novasamatech.github.io/test-runner/4561//#testresult/2d211eee335a0823","status":"failed","statusDetails":"Failed: Timeout 10 when creating connection: Parallel","time":{"start":1705939310924,"stop":1705939310924,"duration":0}},{"uid":"7ee39be6e8588521","reportUrl":"https://novasamatech.github.io/test-runner/4560//#testresult/7ee39be6e8588521","status":"passed","time":{"start":1705924887393,"stop":1705924887393,"duration":0}},{"uid":"fef643b92a6cb328","reportUrl":"https://novasamatech.github.io/test-runner/4559//#testresult/fef643b92a6cb328","status":"passed","time":{"start":1705910486112,"stop":1705910486112,"duration":0}},{"uid":"b7af7776467cb3a","reportUrl":"https://novasamatech.github.io/test-runner/4558//#testresult/b7af7776467cb3a","status":"passed","time":{"start":1705896087067,"stop":1705896087067,"duration":0}},{"uid":"16c0a7295767d191","reportUrl":"https://novasamatech.github.io/test-runner/4557//#testresult/16c0a7295767d191","status":"passed","time":{"start":1705881725270,"stop":1705881725270,"duration":0}},{"uid":"b8a5a3458a1de5b6","reportUrl":"https://novasamatech.github.io/test-runner/4556//#testresult/b8a5a3458a1de5b6","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'get_constant'","time":{"start":1705867294390,"stop":1705867294390,"duration":0}},{"uid":"ab87f63ba8a1a822","reportUrl":"https://novasamatech.github.io/test-runner/4555//#testresult/ab87f63ba8a1a822","status":"broken","statusDetails":"AttributeError: 'NoneType' object has no attribute 'get_constant'","time":{"start":1705852889755,"stop":1705852889755,"duration":0}},{"uid":"8f5e49b396b05f4a","reportUrl":"https://novasamatech.github.io/test-runner/4554//#testresult/8f5e49b396b05f4a","status":"passed","time":{"start":1705838512666,"stop":1705838512666,"duration":0}},{"uid":"95d785ede7d27f54","reportUrl":"https://novasamatech.github.io/test-runner/4553//#testresult/95d785ede7d27f54","status":"passed","time":{"start":1705824084791,"stop":1705824084791,"duration":0}},{"uid":"249daa364cda4ddc","reportUrl":"https://novasamatech.github.io/test-runner/4552//#testresult/249daa364cda4ddc","status":"passed","time":{"start":1705809681537,"stop":1705809681537,"duration":0}},{"uid":"2aaa3811358b9627","reportUrl":"https://novasamatech.github.io/test-runner/4551//#testresult/2aaa3811358b9627","status":"passed","time":{"start":1705795358392,"stop":1705795358392,"duration":0}},{"uid":"834729b96f9d0e69","reportUrl":"https://novasamatech.github.io/test-runner/4550//#testresult/834729b96f9d0e69","status":"passed","time":{"start":1705780880794,"stop":1705780880794,"duration":0}},{"uid":"78f6ac74c1dc99df","reportUrl":"https://novasamatech.github.io/test-runner/4549//#testresult/78f6ac74c1dc99df","status":"passed","time":{"start":1705766482187,"stop":1705766482187,"duration":0}}]},"tags":[]},"source":"91e2897728224363.json","parameterValues":["<scripts.utils.chain_model.Chain object at 0x7f80502a2650>"]}