{"uid":"4e0cf6b2af020579","name":"test_address_prefix[Test for Tinkernet]","fullName":"tests.test_network_parameters.TestNetworkPrefix#test_address_prefix","historyId":"7b196b98ccbf787417ea8275dbeafc77","time":{"start":1669450227283,"stop":1669450227858,"duration":575},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Tinkernet","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fb40fe89970>\nchain = <tests.utils.chain_model.Chain object at 0x7fb40fed96d0>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb40fed96d0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Tinkernet\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Tinkernet","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fb40fe89970>\nchain = <tests.utils.chain_model.Chain object at 0x7fb40fed96d0>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb40fed96d0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Tinkernet\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"467bb63733cf3ce6","name":"stdout","source":"467bb63733cf3ce6.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestNetworkPrefix"},{"name":"host","value":"fv-az238-402"},{"name":"thread","value":"1569-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fb40fed96d0>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"4e0cf6b2af020579.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fb40fed96d0>"]}