{"uid":"888fa40e1efc6a8","name":"test_address_prefix[Test for Encointer]","fullName":"tests.test_network_parameters.TestNetworkPrefix#test_address_prefix","historyId":"06d388d3d9493f7b11d3af8cc69a9ff8","time":{"start":1669449997496,"stop":1669449998584,"duration":1088},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Encointer","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fb40fe7c7c0>\nchain = <tests.utils.chain_model.Chain object at 0x7fb40fed9100>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb40fed9100>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Encointer\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Encointer","statusTrace":"self = <tests.test_network_parameters.TestNetworkPrefix object at 0x7fb40fe7c7c0>\nchain = <tests.utils.chain_model.Chain object at 0x7fb40fed9100>\n\n    def test_address_prefix(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fb40fed9100>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Encointer\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"71ad936b309b3955","name":"stdout","source":"71ad936b309b3955.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestNetworkPrefix"},{"name":"host","value":"fv-az238-402"},{"name":"thread","value":"1569-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fb40fed9100>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"888fa40e1efc6a8.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fb40fed9100>"]}