{"uid":"3dc99a16e86d9c17","name":"test_chainId[Test for Parallel]","fullName":"tests.test_network_parameters.TestChainId#test_chainId","historyId":"1232ee43c10390ecddfd7233e25609cf","time":{"start":1669782249712,"stop":1669782250147,"duration":435},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Parallel","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7f3f260bec40>\nchain = <tests.utils.chain_model.Chain object at 0x7f3f261020a0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f3f261020a0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Parallel\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Parallel","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7f3f260bec40>\nchain = <tests.utils.chain_model.Chain object at 0x7f3f261020a0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f3f261020a0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Parallel\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"e9cdc1d3e8cd7c5a","name":"stdout","source":"e9cdc1d3e8cd7c5a.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestChainId"},{"name":"host","value":"fv-az426-282"},{"name":"thread","value":"1632-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7f3f261020a0>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"3dc99a16e86d9c17.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7f3f261020a0>"]}