{"uid":"7ba3b8d15ff0b859","name":"test_precision[Test for Phala]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"e284fa911e6254e96eae398d20b1eb79","time":{"start":1669884225282,"stop":1669884225967,"duration":685},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f6a0fffbe80>\nchain = <tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Phala\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7f6a0fffbe80>\nchain = <tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Phala\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"9c9d5ebc532751e9","name":"stdout","source":"9c9d5ebc532751e9.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az82-892"},{"name":"thread","value":"1589-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"5c2abce9d0054e7d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669884214582,"stop":1669884215264,"duration":682}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":36,"skipped":0,"passed":247,"unknown":0,"total":283},"items":[{"uid":"e87f929bb066380d","reportUrl":"https://nova-wallet.github.io/test-runner/1999//#testresult/e87f929bb066380d","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669869682239,"stop":1669869682899,"duration":660}},{"uid":"2ecce7f79eb121e0","reportUrl":"https://nova-wallet.github.io/test-runner/1998//#testresult/2ecce7f79eb121e0","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669859238468,"stop":1669859239186,"duration":718}},{"uid":"31f532d596592c33","reportUrl":"https://nova-wallet.github.io/test-runner/1997//#testresult/31f532d596592c33","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669840735464,"stop":1669840736115,"duration":651}},{"uid":"e86d19f05d5e271c","reportUrl":"https://nova-wallet.github.io/test-runner/1996//#testresult/e86d19f05d5e271c","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669826645866,"stop":1669826646538,"duration":672}},{"uid":"4dee90909a4aa3d3","reportUrl":"https://nova-wallet.github.io/test-runner/1995//#testresult/4dee90909a4aa3d3","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669812808974,"stop":1669812809652,"duration":678}},{"uid":"4185dd6117fefd27","reportUrl":"https://nova-wallet.github.io/test-runner/1994//#testresult/4185dd6117fefd27","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669797786621,"stop":1669797787226,"duration":605}},{"uid":"210be406e2530394","reportUrl":"https://nova-wallet.github.io/test-runner/1993//#testresult/210be406e2530394","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669783310193,"stop":1669783310895,"duration":702}},{"uid":"28e606ac025ec035","reportUrl":"https://nova-wallet.github.io/test-runner/1992//#testresult/28e606ac025ec035","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669772233042,"stop":1669772233735,"duration":693}},{"uid":"9016a62475273c53","reportUrl":"https://nova-wallet.github.io/test-runner/1991//#testresult/9016a62475273c53","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669754359337,"stop":1669754360013,"duration":676}},{"uid":"dece9ee523c417f4","reportUrl":"https://nova-wallet.github.io/test-runner/1990//#testresult/dece9ee523c417f4","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669740306121,"stop":1669740306864,"duration":743}},{"uid":"d255c8a195c06caa","reportUrl":"https://nova-wallet.github.io/test-runner/1989//#testresult/d255c8a195c06caa","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669726326538,"stop":1669726327197,"duration":659}},{"uid":"df20ab6b3e621b92","reportUrl":"https://nova-wallet.github.io/test-runner/1988//#testresult/df20ab6b3e621b92","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669711090052,"stop":1669711090735,"duration":683}},{"uid":"a72bc83493d9847a","reportUrl":"https://nova-wallet.github.io/test-runner/1986//#testresult/a72bc83493d9847a","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669685542031,"stop":1669685542781,"duration":750}},{"uid":"c5f454f854fe2add","reportUrl":"https://nova-wallet.github.io/test-runner/1985//#testresult/c5f454f854fe2add","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669667667998,"stop":1669667668655,"duration":657}},{"uid":"1af9d8ef1ec51602","reportUrl":"https://nova-wallet.github.io/test-runner/1984//#testresult/1af9d8ef1ec51602","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669653358305,"stop":1669653358972,"duration":667}},{"uid":"3584ee70b57dfd6a","reportUrl":"https://nova-wallet.github.io/test-runner/1983//#testresult/3584ee70b57dfd6a","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669639706126,"stop":1669639706798,"duration":672}},{"uid":"691d5e468d7d0dec","reportUrl":"https://nova-wallet.github.io/test-runner/1982//#testresult/691d5e468d7d0dec","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669624685357,"stop":1669624686002,"duration":645}},{"uid":"5e8df9fd1a5f1cbf","reportUrl":"https://nova-wallet.github.io/test-runner/1981//#testresult/5e8df9fd1a5f1cbf","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669610216508,"stop":1669610217166,"duration":658}},{"uid":"54018a94ee41f538","reportUrl":"https://nova-wallet.github.io/test-runner/1980//#testresult/54018a94ee41f538","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669598931068,"stop":1669598931737,"duration":669}},{"uid":"4e15ff5e23526758","reportUrl":"https://nova-wallet.github.io/test-runner/1979//#testresult/4e15ff5e23526758","status":"broken","statusDetails":"TimeoutError: [Errno Can't connect to all nodes of network] Phala","time":{"start":1669581232107,"stop":1669581232740,"duration":633}}]},"tags":[]},"source":"7ba3b8d15ff0b859.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7f6a1409f3d0>"]}