{"uid":"c962167486d968ee","name":"test_chainId[Test for Subsocial]","fullName":"tests.test_network_parameters.TestChainId#test_chainId","historyId":"14fdf46db8332282095ecd97945d832b","time":{"start":1667477259864,"stop":1667477261003,"duration":1139},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Subsocial","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fe6abffc8e0>\nchain = <tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Subsocial\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Subsocial","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fe6abffc8e0>\nchain = <tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Subsocial\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"f568424f20815837","name":"stdout","source":"f568424f20815837.txt","type":"text/plain","size":27}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestChainId"},{"name":"host","value":"fv-az119-314"},{"name":"thread","value":"1616-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"c962167486d968ee.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fe6b04e4ac0>"]}