{"uid":"e5c82cb49476c426","name":"test_chainId[Test for QUARTZ]","fullName":"tests.test_network_parameters.TestChainId#test_chainId","historyId":"90d8132868e5a035430fd8d768cc06c1","time":{"start":1670013035145,"stop":1670013036491,"duration":1346},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fd512d399a0>\nchain = <tests.utils.chain_model.Chain object at 0x7fd513214eb0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fd513214eb0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ","statusTrace":"self = <tests.test_network_parameters.TestChainId object at 0x7fd512d399a0>\nchain = <tests.utils.chain_model.Chain object at 0x7fd513214eb0>\n\n    def test_chainId(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fd513214eb0>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] QUARTZ\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"f225cb37d42b731a","name":"stdout","source":"f225cb37d42b731a.txt","type":"text/plain","size":108}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestChainId"},{"name":"host","value":"fv-az459-905"},{"name":"thread","value":"1861-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fd513214eb0>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"e5c82cb49476c426.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fd513214eb0>"]}