{"uid":"6f432fe7720c84b5","name":"test_precision[Test for Darwinia]","fullName":"tests.test_network_parameters.TestPrecision#test_precision","historyId":"104a5db209b471752261d1de548047ac","time":{"start":1669740408785,"stop":1669740409954,"duration":1169},"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Darwinia","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fca445c4a60>\nchain = <tests.utils.chain_model.Chain object at 0x7fca446a9790>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fca446a9790>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Darwinia\n\ntests/utils/chain_model.py:29: TimeoutError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"TimeoutError: [Errno Can't connect to all nodes of network] Darwinia","statusTrace":"self = <tests.test_network_parameters.TestPrecision object at 0x7fca445c4a60>\nchain = <tests.utils.chain_model.Chain object at 0x7fca446a9790>\n\n    def test_precision(self, chain: Chain):\n>       chain.create_connection()\n\ntests/test_network_parameters.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.chain_model.Chain object at 0x7fca446a9790>\n\n    def create_connection(self):\n        for node in self.nodes:\n            if (self.substrate):\n                return self.substrate\n            try:\n                self.substrate = create_connection_by_url(node.get('url'))\n                return self.substrate\n            except:\n                print(\"Can't connect to that node\")\n                continue\n    \n>       raise TimeoutError(\"Can't connect to all nodes of network\", self.name)\nE       TimeoutError: [Errno Can't connect to all nodes of network] Darwinia\n\ntests/utils/chain_model.py:29: TimeoutError","steps":[],"attachments":[{"uid":"d7af1a38f4877768","name":"stdout","source":"d7af1a38f4877768.txt","type":"text/plain","size":54}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_network_parameters"},{"name":"subSuite","value":"TestPrecision"},{"name":"host","value":"fv-az573-131"},{"name":"thread","value":"1571-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_network_parameters"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"chain","value":"<tests.utils.chain_model.Chain object at 0x7fca446a9790>"}],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"6f432fe7720c84b5.json","parameterValues":["<tests.utils.chain_model.Chain object at 0x7fca446a9790>"]}